export const MODES = {
  CHATGPT: 'chatgpt',
  CLAUDE: 'claude',
  MIDJOURNEY: 'midjourney',
};

export function compilePrompt(mode, variables) {
  switch (mode) {
    case MODES.CHATGPT:
      return compileChatGPT(variables);
    case MODES.CLAUDE:
      return compileClaude(variables);
    case MODES.MIDJOURNEY:
      return compileMidjourney(variables);
    default:
      return '';
  }
}

function compileChatGPT(v) {
  const parts = [];

  if (v.role) {
    parts.push(`# Role / Persona\n${v.role}\n`);
  }
  if (v.task) {
    parts.push(`## Core Task / Objective\n${v.task}\n`);
  }
  if (v.context) {
    parts.push(`### Background Context\n${v.context}\n`);
  }
  if (v.constraints) {
    parts.push(`#### Strict Output Constraints\n${v.constraints}\n`);
  }

  parts.push(`---\n> System Boundary: This prompt is auto-generated by Free Prompt Studio.\n> Do not deviate from the requested format above.`);

  return parts.join('\n');
}

function compileClaude(v) {
  const parts = [];

  parts.push('<prompt>');

  if (v.role) {
    parts.push(`  <context>\n    <role>${v.role}</role>\n  </context>`);
  }
  if (v.task) {
    parts.push(`  <instructions>\n    <task>${v.task}</task>\n  </instructions>`);
  }
  if (v.context) {
    parts.push(`  <background>\n    ${v.context}\n  </background>`);
  }
  if (v.constraints) {
    parts.push(`  <guardrails>\n    ${v.constraints}\n  </guardrails>`);
  }

  parts.push('</prompt>');

  return parts.join('\n\n');
}

function compileMidjourney(v) {
  const parts = [];

  if (v.role) {
    parts.push(`Subject / Style: ${v.role}`);
  }
  if (v.task) {
    parts.push(`Scene / Action: ${v.task}`);
  }
  if (v.context) {
    parts.push(`Environment / Mood: ${v.context}`);
  }

  parts.push(`--ar 16:9 --v 6.0 --style raw --s 250`);

  if (v.constraints) {
    parts.push(`[Exclusions: ${v.constraints}]`);
  }

  return parts.join('\n');
}
